on:
  [ push, pull_request ]

env:
  BUILD_TYPE: Debug

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.3'
          host: 'linux'

      - name: Install GoogleTest
        run: |
          cd ~
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
          make -j8
          sudo make install
          sudo ldconfig

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          boost_version: 1.81.0
          platform_version: 22.04
          toolset: gcc
          arch: x86

      - name: Configure CMake
        run: |
          sudo /sbin/ldconfig -v
          export Boost_ROOT=/home/runner/work/2023_1_Holi/2023_1_Holi/boost
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_FOR_TEST=1

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --extra-verbose
